name: add-project
# This workflow gets executed when someone opens an issue for adding a project
on:
  issues:
      types: [opened,edited]
jobs:
   add_project_job:
    name: add-project
    if: startsWith( ${{ github.event.issue.title }},"add")||startsWith( ${{ github.event.issue.title }},"update") 
    runs-on: ubuntu-latest
    steps:
    - name: setup directory
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y python-setuptools
        pip3 install PyGithub  
    - name: A job to add or update a project
      id: addProject
      run: | 
        echo ::set-output name=issue_comment::`python3 add_name.py '${{ github.event.issue.user.login }}' '${{ github.event.issue.body }}'`
        git config user.name shriaas2898
        git add .
        git commit -m "Added: ${{ github.event.issue.title }}"
        git push
    - name: Close Issue
      if: startsWith( ${{ github.event.issue.title }},"add")||startsWith( ${{ github.event.issue.title }},"update") 
      uses: peter-evans/close-issue@v1
      with:
          issue-number: ${{ github.event.issue.number }}
          comment: ${{ steps.addProject.outputs.issue_comment }}
