on: [issue]
  types: [opened]
jobs:
  add_project_job:
    runs-on: ubuntu-latest
    shell: bash
    name: A job to add or update a project
    run: python3 add-name.py ${{ github.event.issue.title }} ${{ github.event.issue.title }}
