name: test-file
on: [push]
jobs:
  check_directory_and_list_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: setup-directory
        uses: actions/checkout@v2
        
      - name: find-files
        run: |
            pwd
            ls -a
            find README.md
